In [ ]:
import pandas as pd

file_path = '/content/Titanic-Dataset.csv'
titanic_df = pd.read_csv(file_path)

In [ ]:
import pandas as pd

# Load the Titanic dataset
file_path = '/content/Titanic-Dataset.csv'
titanic_df = pd.read_csv(file_path)

# Display the first few rows of the 'PassengerId' and 'Survived' columns
print(titanic_df[['PassengerId', 'Survived']].head())

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Fill missing values in 'Age' with the median age
titanic_df['Age'].fillna(titanic_df['Age'].median(), inplace=True)

# Fill missing values in 'Embarked' with the mode
titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode()[0], inplace=True)

# Drop the 'Cabin' column due to a high number of missing values
titanic_df.drop('Cabin', axis=1, inplace=True)

# Convert 'Sex' to numerical values
titanic_df['Sex'] = titanic_df['Sex'].map({'male': 0, 'female': 1})

# Convert 'Embarked' to numerical values using one-hot encoding
titanic_df = pd.get_dummies(titanic_df, columns=['Embarked'], drop_first=True)

# Drop irrelevant columns
titanic_df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

In [ ]:
from sklearn.model_selection import train_test_split

X = titanic_df.drop('Survived', axis=1)
y = titanic_df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

NameError: name 'titanic_df' is not defined

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [ ]:
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(classification_report(y_test, y_pred))

Accuracy: 0.7988826815642458
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       105
           1       0.76      0.74      0.75        74

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179